import { User, UserRole } from '@/types/auth';
import { WorkflowApplication, Notification, EDSQuery } from '@/types/workflow';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Admin Officer',
    email: 'admin@moef.gov.in',
    role: 'admin',
    department: 'MoEFCC Headquarters',
    designation: 'System Administrator',
    isActive: true,
  },
  {
    id: 'u2',
    name: 'Ravi Kumar',
    email: 'proponent@company.com',
    role: 'applicant',
    department: 'Greenfield Infrastructure Pvt. Ltd.',
    designation: 'Project Manager',
    isActive: true,
  },
  {
    id: 'u3',
    name: 'Dr. Priya Sharma',
    email: 'scrutiny@moef.gov.in',
    role: 'scrutiny',
    department: 'MoEFCC - Industry Division',
    designation: 'Senior Scientific Officer',
    isActive: true,
  },
  {
    id: 'u4',
    name: 'Suresh Menon',
    email: 'mom@moef.gov.in',
    role: 'mom',
    department: 'MoEFCC - EAC Secretariat',
    designation: 'Section Officer',
    isActive: true,
  },
];

export const MOCK_PASSWORDS: Record<string, string> = {
  'admin@moef.gov.in': 'admin123',
  'proponent@company.com': 'proponent123',
  'scrutiny@moef.gov.in': 'scrutiny123',
  'mom@moef.gov.in': 'mom123',
};

const baseEDS: EDSQuery[] = [
  {
    id: 'eds1',
    queryNumber: 'EDS-001',
    subject: 'Water Requirement Details',
    description:
      'Please provide detailed water balance sheet including source, quantum, treatment requirements and disposal of wastewater during construction and operation phase.',
    raisedAt: '2026-02-10T10:00:00Z',
    raisedBy: 'scrutiny@moef.gov.in',
    status: 'open',
  },
  {
    id: 'eds2',
    queryNumber: 'EDS-002',
    subject: 'Air Quality Baseline Data',
    description:
      'Baseline ambient air quality data (PM10, PM2.5, NOx, SO2, CO) for pre-project period (minimum one season) is required. Please attach monitoring reports.',
    raisedAt: '2026-02-11T09:30:00Z',
    raisedBy: 'scrutiny@moef.gov.in',
    response:
      'We have attached the NABL-accredited lab reports for ambient air quality monitoring conducted during winter season (Nov 2025 – Jan 2026).',
    respondedAt: '2026-02-18T15:00:00Z',
    status: 'responded',
  },
];

export const MOCK_APPLICATIONS: WorkflowApplication[] = [
  {
    id: 'app1',
    applicationNumber: 'MoEFCC/EC/2026/00001',
    projectName: 'Greenfield Cement Plant – Phase II',
    proponentName: 'Ravi Kumar',
    proponentEmail: 'proponent@company.com',
    proponentPhone: '9876543210',
    projectCategory: 'A',
    projectSector: 'Cement',
    stateUT: 'Rajasthan',
    district: 'Jodhpur',
    projectCost: 4500000000,
    projectArea: 250,
    status: 'eds_raised',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-02-11T09:30:00Z',
    submittedAt: '2026-01-20T12:00:00Z',
    scrutinyAssignedTo: 'scrutiny@moef.gov.in',
    edsQueries: baseEDS,
    remarks: 'Pending response to EDS queries.',
    paymentStatus: 'paid',
    paymentAmount: 50000,
    paymentTransactionId: 'TXN2026012001',
    documents: [
      {
        id: 'doc1',
        name: 'EIA_Report_Cement_Plant.pdf',
        type: 'application/pdf',
        size: 5242880,
        url: '#',
        uploadedAt: '2026-01-19T11:00:00Z',
        uploadedBy: 'proponent@company.com',
      },
      {
        id: 'doc2',
        name: 'Site_Plan.pdf',
        type: 'application/pdf',
        size: 2097152,
        url: '#',
        uploadedAt: '2026-01-19T11:05:00Z',
        uploadedBy: 'proponent@company.com',
      },
    ],
  },
  {
    id: 'app2',
    applicationNumber: 'MoEFCC/EC/2026/00002',
    projectName: 'Solar Power Park – 200 MW',
    proponentName: 'Ravi Kumar',
    proponentEmail: 'proponent@company.com',
    proponentPhone: '9876543210',
    projectCategory: 'B1',
    projectSector: 'Power',
    stateUT: 'Gujarat',
    district: 'Kutch',
    projectCost: 1200000000,
    projectArea: 500,
    status: 'draft',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    edsQueries: [],
    paymentStatus: 'pending',
    documents: [],
  },
  {
    id: 'app3',
    applicationNumber: 'MoEFCC/EC/2025/00876',
    projectName: 'National Highway Expansion – NH-48',
    proponentName: 'NHAI Representative',
    proponentEmail: 'nhai@gov.in',
    proponentPhone: '9811223344',
    projectCategory: 'A',
    projectSector: 'Road / Highway',
    stateUT: 'Karnataka',
    district: 'Bengaluru Rural',
    projectCost: 8900000000,
    projectArea: 120,
    status: 'referred',
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-02-25T14:00:00Z',
    submittedAt: '2025-11-10T09:00:00Z',
    finalizedAt: undefined,
    scrutinyAssignedTo: 'scrutiny@moef.gov.in',
    edsQueries: [],
    remarks: 'Referred to EAC for technical appraisal.',
    meetingDate: '2026-03-20',
    meetingNumber: 'EAC-2026-03/07',
    paymentStatus: 'verified',
    paymentAmount: 100000,
    paymentTransactionId: 'TXN2025111001',
    documents: [
      {
        id: 'doc3',
        name: 'EIA_NH48.pdf',
        type: 'application/pdf',
        size: 10485760,
        url: '#',
        uploadedAt: '2025-11-09T10:00:00Z',
        uploadedBy: 'nhai@gov.in',
      },
    ],
    gist: {
      id: 'gist3',
      applicationId: 'app3',
      projectBackground:
        'The NH-48 expansion project aims to widen the existing 4-lane highway to 6 lanes between Bengaluru and Mysuru to reduce traffic congestion and improve connectivity.',
      proposalDetails:
        'Total length: 118 km. Land acquisition: 450 hectares. Construction period: 36 months.',
      environmentalImpact:
        'Project involves felling of 2,340 trees. Three water bodies fall within the project corridor.',
      mitigationMeasures:
        'Compensatory afforestation planned at 1:3 ratio. Culverts and underpasses for wildlife. Noise barriers at sensitive receptors.',
      recommendation: 'Recommended for grant of EC with standard conditions.',
      generatedAt: '2026-02-26T10:00:00Z',
      isLocked: false,
    },
  },
  {
    id: 'app4',
    applicationNumber: 'MoEFCC/EC/2025/00654',
    projectName: 'Coal Mining Project – Block C',
    proponentName: 'CIL Subsidiary',
    proponentEmail: 'cil@subsidiary.in',
    proponentPhone: '7890123456',
    projectCategory: 'A',
    projectSector: 'Mining',
    stateUT: 'Jharkhand',
    district: 'Ramgarh',
    projectCost: 15000000000,
    projectArea: 800,
    status: 'finalized',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-01-15T16:00:00Z',
    submittedAt: '2025-06-15T09:00:00Z',
    finalizedAt: '2026-01-15T16:00:00Z',
    scrutinyAssignedTo: 'scrutiny@moef.gov.in',
    edsQueries: [],
    remarks: 'EC granted. Certificate issued.',
    paymentStatus: 'verified',
    paymentAmount: 200000,
    paymentTransactionId: 'TXN2025061501',
    documents: [],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u2',
    title: 'EDS Query Raised',
    message:
      'Scrutiny officer has raised EDS Query EDS-001 on your application MoEFCC/EC/2026/00001.',
    type: 'warning',
    isRead: false,
    createdAt: '2026-02-10T10:05:00Z',
    applicationId: 'app1',
  },
  {
    id: 'n2',
    userId: 'u3',
    title: 'Application Submitted',
    message: 'Application MoEFCC/EC/2026/00001 has been submitted and is pending scrutiny.',
    type: 'info',
    isRead: true,
    createdAt: '2026-01-20T12:05:00Z',
    applicationId: 'app1',
  },
  {
    id: 'n3',
    userId: 'u4',
    title: 'Application Referred for EAC',
    message: 'Application MoEFCC/EC/2025/00876 has been referred for EAC appraisal.',
    type: 'info',
    isRead: false,
    createdAt: '2026-02-25T14:05:00Z',
    applicationId: 'app3',
  },
];
